services:
  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "mammotab_execution_mongo"
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    logging:
      driver: none
    volumes:
      - ./mongo-data:/data/db

  jupyter:
    build: .
    container_name: mammotab_execution_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      RESTARTABLE: "yes"
    env_file:
      - ./.env
    depends_on:
      - mongo
    volumes:
      - ./work:/home/jovyan/work
      - ./my-data:/data/my-data
